"""Add researcher_id to herb table

Revision ID: 29434d76ae52
Revises: 
Create Date: 2025-01-26 12:49:55.041988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29434d76ae52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('researcher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_herb_researcher_id', 'user', ['researcher_id'], ['id'])
        batch_op.drop_column('watering')
        batch_op.drop_column('family')
        batch_op.drop_column('propagation_methods')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propagation_methods', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('family', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('watering', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_herb_researcher_id', type_='foreignkey')
        batch_op.drop_column('researcher_id')

    # ### end Alembic commands ###
